behaviors:
  AIBehavior:
    trainer_type: ppo
    time_horizon: 128
    max_steps: 1.0e7
    hyperparameters:
      batch_size: 512
      buffer_size: 2048
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.0003
      num_epoch: 3
    network_settings:
      num_layers: 2
      hidden_units: 512
      normalize: false
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 256
      gail:
        strength: 0.01
        gamma: 0.99
        demo_path: /Users/sungho/Documents/GitHub/RoomDesign/Assets/Script/MiniGame/Find/AIBehavior_0.demo
    behavioral_cloning:
      demo_path: /Users/sungho/Documents/GitHub/RoomDesign/Assets/Script/MiniGame/Find/AIBehavior_0.demo 
      strength: 0.5
      steps: 150000